# AUTO GENERATED FILE - DO NOT EDIT

#' @export
multiDatePicker <- function(id=NULL, animations=NULL, arrow=NULL, arrowClassName=NULL, arrowStyle=NULL, buttons=NULL, calendar=NULL, calendarPosition=NULL, className=NULL, containerClassName=NULL, containerStyle=NULL, currentDate=NULL, digits=NULL, disableDayPicker=NULL, disableMonthPicker=NULL, disableYearPicker=NULL, disabled=NULL, displayWeekNumbers=NULL, editable=NULL, fixMainPosition=NULL, fixRelativePosition=NULL, format=NULL, formattingIgnoreList=NULL, fullYear=NULL, hideMonth=NULL, hideOnScroll=NULL, hideYear=NULL, inputClass=NULL, inputMode=NULL, locale=NULL, mapDays=NULL, maxDate=NULL, minDate=NULL, mobileButtons=NULL, mobileLabels=NULL, months=NULL, multiple=NULL, name=NULL, numberOfMonths=NULL, offsetX=NULL, offsetY=NULL, onChange=NULL, onClose=NULL, onFocusedDateChange=NULL, onMonthChange=NULL, onOpen=NULL, onOpenPickNewDate=NULL, onPositionChange=NULL, onPropsChange=NULL, onYearChange=NULL, onlyMonthPicker=NULL, onlyShowInRangeDates=NULL, onlyYearPicker=NULL, placeholder=NULL, plugins=NULL, portal=NULL, portalTarget=NULL, range=NULL, rangeHover=NULL, readOnly=NULL, render=NULL, renderButton=NULL, scrollSensitive=NULL, shadow=NULL, showOtherDays=NULL, sort=NULL, style=NULL, title=NULL, value=NULL, weekDays=NULL, weekNumber=NULL, weekPicker=NULL, weekStartDayIndex=NULL, zIndex=NULL) {
    
    props <- list(id=id, animations=animations, arrow=arrow, arrowClassName=arrowClassName, arrowStyle=arrowStyle, buttons=buttons, calendar=calendar, calendarPosition=calendarPosition, className=className, containerClassName=containerClassName, containerStyle=containerStyle, currentDate=currentDate, digits=digits, disableDayPicker=disableDayPicker, disableMonthPicker=disableMonthPicker, disableYearPicker=disableYearPicker, disabled=disabled, displayWeekNumbers=displayWeekNumbers, editable=editable, fixMainPosition=fixMainPosition, fixRelativePosition=fixRelativePosition, format=format, formattingIgnoreList=formattingIgnoreList, fullYear=fullYear, hideMonth=hideMonth, hideOnScroll=hideOnScroll, hideYear=hideYear, inputClass=inputClass, inputMode=inputMode, locale=locale, mapDays=mapDays, maxDate=maxDate, minDate=minDate, mobileButtons=mobileButtons, mobileLabels=mobileLabels, months=months, multiple=multiple, name=name, numberOfMonths=numberOfMonths, offsetX=offsetX, offsetY=offsetY, onChange=onChange, onClose=onClose, onFocusedDateChange=onFocusedDateChange, onMonthChange=onMonthChange, onOpen=onOpen, onOpenPickNewDate=onOpenPickNewDate, onPositionChange=onPositionChange, onPropsChange=onPropsChange, onYearChange=onYearChange, onlyMonthPicker=onlyMonthPicker, onlyShowInRangeDates=onlyShowInRangeDates, onlyYearPicker=onlyYearPicker, placeholder=placeholder, plugins=plugins, portal=portal, portalTarget=portalTarget, range=range, rangeHover=rangeHover, readOnly=readOnly, render=render, renderButton=renderButton, scrollSensitive=scrollSensitive, shadow=shadow, showOtherDays=showOtherDays, sort=sort, style=style, title=title, value=value, weekDays=weekDays, weekNumber=weekNumber, weekPicker=weekPicker, weekStartDayIndex=weekStartDayIndex, zIndex=zIndex)
    if (length(props) > 0) {
        props <- props[!vapply(props, is.null, logical(1))]
    }
    component <- list(
        props = props,
        type = 'MultiDatePicker',
        namespace = 'multi_date_picker',
        propNames = c('id', 'animations', 'arrow', 'arrowClassName', 'arrowStyle', 'buttons', 'calendar', 'calendarPosition', 'className', 'containerClassName', 'containerStyle', 'currentDate', 'digits', 'disableDayPicker', 'disableMonthPicker', 'disableYearPicker', 'disabled', 'displayWeekNumbers', 'editable', 'fixMainPosition', 'fixRelativePosition', 'format', 'formattingIgnoreList', 'fullYear', 'hideMonth', 'hideOnScroll', 'hideYear', 'inputClass', 'inputMode', 'locale', 'mapDays', 'maxDate', 'minDate', 'mobileButtons', 'mobileLabels', 'months', 'multiple', 'name', 'numberOfMonths', 'offsetX', 'offsetY', 'onChange', 'onClose', 'onFocusedDateChange', 'onMonthChange', 'onOpen', 'onOpenPickNewDate', 'onPositionChange', 'onPropsChange', 'onYearChange', 'onlyMonthPicker', 'onlyShowInRangeDates', 'onlyYearPicker', 'placeholder', 'plugins', 'portal', 'portalTarget', 'range', 'rangeHover', 'readOnly', 'render', 'renderButton', 'scrollSensitive', 'shadow', 'showOtherDays', 'sort', 'style', 'title', 'value', 'weekDays', 'weekNumber', 'weekPicker', 'weekStartDayIndex', 'zIndex'),
        package = 'multiDatePicker'
        )

    structure(component, class = c('dash_component', 'list'))
}
